using System.Diagnostics;
using System.Security.Cryptography;
using HaloMeister.App.Localization;

namespace HaloMeister.App.Services;

/// <summary>
/// Bundled campaign content mod <c>MMYJ_FULL_VEHI_WAP_P</c> (.utoc/.ucas/.pak):
/// full vehicle/weapon palettes, AI character-palette fill (schema max 64),
/// dedicated <c>hm_ally</c>/<c>hm_hostile</c> spawn scaffolds, plus Superior
/// Marines / Covenant character AI overlays. Dedicated Allegiance
/// Demo features require the complete triplet in the game Paks folder;
/// vehicle/weapon tools remain usable without it.
/// </summary>
public sealed class FullPalettesOverlayService
{
    public const string OverlayStem = "MMYJ_FULL_VEHI_WAP_P";

    // Previous shipping names; cleaned up on install/remove so old copies
    // do not keep mounting after a rename or after demo-squads were merged in.
    private const string LegacyOverlayStem = "HM_FullPalettes_P";
    private const string LegacyDemoSquadsStem = "ZZ_HM_DemoSquads_P";
    private const string LegacyDemoSquadsStemAlt = "HM_DemoSquads_P";

    private static readonly string[] Extensions = [".utoc", ".ucas", ".pak"];

    /// <summary>
    /// Trusted fingerprint of the shipping triplet shipped with this build
    /// (<c>length:SHA256</c> for .utoc|.ucas|.pak). Regenerated by
    /// <c>expand-palettes.ps1 -UpdateBundledAssets</c>.
    /// </summary>
    public const string ExpectedBundledFingerprint =
        "17432:C965F6F1FD998134852160CD2B5B369BDA7C8732CE142C6D48B002A399F78F0D|83337762:E6410B84F71103C9BDD3552AD6461E58F5EF84C2B259A08464DFDF37C94F9844|339:B712C03A695E34CD522446B73C4F71644A402FF141EB19CE66C269FD5676AD8C";

    private static readonly object FingerprintCacheGate = new();
    private static string? _fingerprintCacheKey;
    private static string? _fingerprintCacheValue;

    public static IReadOnlyList<string> RequiredFileNames { get; } =
        Extensions.Select(extension => OverlayStem + extension).ToArray();

    public bool IsGameRunning =>
        Process.GetProcessesByName("HaloCampaignEvolved").Any(process => !process.HasExited);

    /// <summary>
    /// True only when all three overlay files are present in Paks.
    /// Dedicated features (Allegiance Demo scaffolds) should gate on this.
    /// </summary>
    public bool IsInstalled()
    {
        try
        {
            string paks = ResolvePaksDirectory();
            return HasCompleteTriplet(paks, OverlayStem) ||
                   HasCompleteTriplet(paks, LegacyOverlayStem);
        }
        catch (DirectoryNotFoundException)
        {
            return false;
        }
    }

    public bool IsBundledAvailable()
    {
        try
        {
            _ = ResolveBundledSources();
            return true;
        }
        catch (FileNotFoundException)
        {
            return false;
        }
    }

    /// <summary>
    /// True when the app-bundled triplet matches the trusted fingerprint for
    /// this build. Tampered or corrupt bundles must not drive update prompts.
    /// </summary>
    public bool IsBundledIntact()
    {
        try
        {
            string[] sources = ResolveBundledSources();
            string? fingerprint = TryFingerprintFiles(sources);
            return fingerprint is not null &&
                   string.Equals(
                       fingerprint,
                       ExpectedBundledFingerprint,
                       StringComparison.Ordinal);
        }
        catch (FileNotFoundException)
        {
            return false;
        }
    }

    /// <summary>
    /// Compare bundled vs installed content. When the app bundle is tampered,
    /// returns <see cref="BuiltinModSyncState.BundleTampered"/> and never
    /// reports <see cref="BuiltinModSyncState.Outdated"/>.
    /// </summary>
    public BuiltinModSyncStatus GetSyncStatus()
    {
        string[]? bundledSources = null;
        try
        {
            bundledSources = ResolveBundledSources();
        }
        catch (FileNotFoundException)
        {
            return new BuiltinModSyncStatus(
                BuiltinModSyncState.BundleMissing,
                CanInstall: false,
                CanRemove: false,
                NeedsUpdatePrompt: false,
                L.Get("builtin_mod.bundle_missing"));
        }

        string? bundledFingerprint = TryFingerprintFiles(bundledSources);
        bool bundledIntact =
            bundledFingerprint is not null &&
            string.Equals(
                bundledFingerprint,
                ExpectedBundledFingerprint,
                StringComparison.Ordinal);

        string? paks = null;
        try
        {
            paks = ResolvePaksDirectory();
        }
        catch (DirectoryNotFoundException)
        {
            if (!bundledIntact)
            {
                return new BuiltinModSyncStatus(
                    BuiltinModSyncState.BundleTampered,
                    CanInstall: false,
                    CanRemove: false,
                    NeedsUpdatePrompt: false,
                    L.Get("builtin_mod.bundle_tampered"));
            }

            return new BuiltinModSyncStatus(
                BuiltinModSyncState.GameFolderMissing,
                CanInstall: false,
                CanRemove: false,
                NeedsUpdatePrompt: false,
                L.Get("builtin_mod.game_folder_missing"));
        }

        int present = RequiredFileNames.Count(name =>
            File.Exists(Path.Combine(paks, name)));
        bool shippingInstalled = HasCompleteTriplet(paks, OverlayStem);
        bool legacyInstalled = HasCompleteTriplet(paks, LegacyOverlayStem);
        bool anyInstalledFiles = present > 0 ||
            Extensions.Any(extension =>
                File.Exists(Path.Combine(paks, LegacyOverlayStem + extension)) ||
                File.Exists(Path.Combine(paks, LegacyDemoSquadsStem + extension)) ||
                File.Exists(Path.Combine(paks, LegacyDemoSquadsStemAlt + extension)));

        if (!bundledIntact)
        {
            return new BuiltinModSyncStatus(
                BuiltinModSyncState.BundleTampered,
                CanInstall: false,
                CanRemove: anyInstalledFiles,
                NeedsUpdatePrompt: false,
                L.Get("builtin_mod.bundle_tampered"));
        }

        if (shippingInstalled)
        {
            string? installedFingerprint = TryFingerprintTriplet(paks, OverlayStem);
            if (installedFingerprint is not null &&
                string.Equals(
                    installedFingerprint,
                    bundledFingerprint,
                    StringComparison.Ordinal))
            {
                return new BuiltinModSyncStatus(
                    BuiltinModSyncState.UpToDate,
                    CanInstall: false,
                    CanRemove: true,
                    NeedsUpdatePrompt: false,
                    L.Get("builtin_mod.status_ready"));
            }

            return new BuiltinModSyncStatus(
                BuiltinModSyncState.Outdated,
                CanInstall: true,
                CanRemove: true,
                NeedsUpdatePrompt: true,
                L.Get("builtin_mod.status_outdated"));
        }

        if (legacyInstalled)
        {
            return new BuiltinModSyncStatus(
                BuiltinModSyncState.Outdated,
                CanInstall: true,
                CanRemove: true,
                NeedsUpdatePrompt: true,
                L.Get("builtin_mod.status_outdated"));
        }

        if (present == 0)
        {
            return new BuiltinModSyncStatus(
                BuiltinModSyncState.NotInstalled,
                CanInstall: true,
                CanRemove: anyInstalledFiles,
                NeedsUpdatePrompt: false,
                L.Get("builtin_mod.status_not_installed"));
        }

        return new BuiltinModSyncStatus(
            BuiltinModSyncState.Incomplete,
            CanInstall: true,
            CanRemove: true,
            NeedsUpdatePrompt: true,
            L.Format(
                "builtin_mod.status_incomplete",
                present,
                RequiredFileNames.Count));
    }

    /// <summary>
    /// Per-file presence for the shipping stem in the game Paks folder.
    /// </summary>
    public IReadOnlyList<BuiltinModFileStatus> GetInstalledFileStatus()
    {
        string? paks = null;
        try { paks = ResolvePaksDirectory(); }
        catch (DirectoryNotFoundException) { }

        return RequiredFileNames
            .Select(name => new BuiltinModFileStatus(
                name,
                paks is not null && File.Exists(Path.Combine(paks, name))))
            .ToArray();
    }

    private static bool HasCompleteTriplet(string paks, string stem) =>
        Extensions.All(extension =>
            File.Exists(Path.Combine(paks, stem + extension)));

    private static string? TryFingerprintTriplet(string directory, string stem)
    {
        string[] paths = Extensions
            .Select(extension => Path.Combine(directory, stem + extension))
            .ToArray();
        return TryFingerprintFiles(paths);
    }

    private static string? TryFingerprintFiles(IReadOnlyList<string> paths)
    {
        try
        {
            string cacheKey = string.Join(
                '|',
                paths.Select(path =>
                {
                    var info = new FileInfo(path);
                    return $"{path}:{info.Length}:{info.LastWriteTimeUtc.Ticks}";
                }));
            lock (FingerprintCacheGate)
            {
                if (_fingerprintCacheKey == cacheKey &&
                    _fingerprintCacheValue is not null)
                {
                    return _fingerprintCacheValue;
                }
            }

            var parts = new List<string>(paths.Count);
            foreach (string path in paths)
            {
                var info = new FileInfo(path);
                using FileStream stream = File.OpenRead(path);
                byte[] hash = SHA256.HashData(stream);
                parts.Add($"{info.Length}:{Convert.ToHexString(hash)}");
            }

            string fingerprint = string.Join('|', parts);
            lock (FingerprintCacheGate)
            {
                _fingerprintCacheKey = cacheKey;
                _fingerprintCacheValue = fingerprint;
            }
            return fingerprint;
        }
        catch
        {
            return null;
        }
    }

    public FullPalettesOverlayResult Install()
    {
        EnsureGameClosed();
        string[] sources = ResolveBundledSources();
        string? bundledFingerprint = TryFingerprintFiles(sources);
        if (bundledFingerprint is null ||
            !string.Equals(
                bundledFingerprint,
                ExpectedBundledFingerprint,
                StringComparison.Ordinal))
        {
            throw new InvalidOperationException(
                L.Get("builtin_mod.bundle_tampered"));
        }

        string paks = ResolvePaksDirectory();
        RemoveStem(paks, LegacyOverlayStem);
        RemoveStem(paks, LegacyDemoSquadsStem);
        RemoveStem(paks, LegacyDemoSquadsStemAlt);
        RemoveStem(paks, OverlayStem);
        string[] destinations = sources
            .Select(source => Path.Combine(paks, Path.GetFileName(source)))
            .ToArray();

        var copied = new List<string>();
        try
        {
            for (int index = 0; index < sources.Length; index++)
            {
                string temporary = destinations[index] + $".{Guid.NewGuid():N}.tmp";
                File.Copy(sources[index], temporary, false);
                File.Move(temporary, destinations[index], true);
                copied.Add(destinations[index]);
            }
        }
        catch
        {
            foreach (string file in copied)
            {
                try { File.Delete(file); }
                catch { }
            }
            throw;
        }

        return new FullPalettesOverlayResult(
            Installed: true,
            PaksDirectory: paks,
            Files: destinations,
            Message: L.Get("builtin_mod.installed_restart"));
    }

    public FullPalettesOverlayResult Remove()
    {
        EnsureGameClosed();
        string paks = ResolvePaksDirectory();
        var removed = new List<string>();
        removed.AddRange(RemoveStem(paks, OverlayStem));
        removed.AddRange(RemoveStem(paks, LegacyOverlayStem));
        removed.AddRange(RemoveStem(paks, LegacyDemoSquadsStem));
        removed.AddRange(RemoveStem(paks, LegacyDemoSquadsStemAlt));

        if (removed.Count == 0)
            throw new FileNotFoundException(
                L.Get("builtin_mod.status_not_installed"));

        return new FullPalettesOverlayResult(
            Installed: false,
            PaksDirectory: paks,
            Files: removed,
            Message: L.Get("builtin_mod.removed_restart"));
    }

    private void EnsureGameClosed()
    {
        if (IsGameRunning)
            throw new InvalidOperationException(
                L.Get("builtin_mod.close_game"));
    }

    private static List<string> RemoveStem(string paks, string stem)
    {
        var removed = new List<string>();
        foreach (string extension in Extensions)
        {
            string path = Path.Combine(paks, stem + extension);
            if (!File.Exists(path)) continue;
            File.Delete(path);
            removed.Add(path);
        }
        return removed;
    }

    private static string[] ResolveBundledSources()
    {
        string[] roots =
        [
            Path.Combine(AppContext.BaseDirectory, "Assets", "Overlays"),
            Path.Combine(AppContext.BaseDirectory, "Overlays"),
        ];
        foreach (string root in roots)
        {
            string[] candidates = Extensions
                .Select(extension => Path.Combine(root, OverlayStem + extension))
                .ToArray();
            if (candidates.All(File.Exists))
                return candidates;
        }

        throw new FileNotFoundException(
            L.Get("builtin_mod.bundle_missing"));
    }

    public static string ResolvePaksDirectory()
    {
        string? discovered = GameInstallationService.Current.TryGetPaksDirectory();
        if (discovered is not null)
            return discovered;

        foreach (string root in CandidateGameRoots())
        {
            string full;
            try { full = Path.GetFullPath(root); }
            catch { continue; }

            string[] candidates =
            [
                Path.Combine(full, "Content", "Meteorite", "Content", "Paks"),
                Path.Combine(full, "Meteorite", "Content", "Paks"),
                Path.Combine(full, "Content", "Paks"),
                full,
            ];
            foreach (string candidate in candidates)
                if (Directory.Exists(candidate) &&
                    Directory.EnumerateFiles(candidate, "*.utoc").Any())
                    return candidate;
        }

        throw new DirectoryNotFoundException(
            L.Get("builtin_mod.game_folder_missing"));
    }

    private static IEnumerable<string> CandidateGameRoots()
    {
        string? remembered = TryRememberedGameRoot();
        if (!string.IsNullOrWhiteSpace(remembered))
            yield return remembered!;

        foreach (string root in GameInstallationService.Current.EnumerateCandidateRoots())
            yield return root;
    }

    private static string? TryRememberedGameRoot()
    {
        try
        {
            // Binary directory is already the WinGDK/Win64 folder; walking from there
            // reaches Content\Meteorite\Content\Paks in a few hops.
            string? binaryDirectory = GameInstallationService.Current.BinaryDirectory;
            if (!string.IsNullOrWhiteSpace(binaryDirectory))
            {
                string? fromBinary = WalkToGameRoot(binaryDirectory);
                if (fromBinary is not null)
                    return fromBinary;
            }

            string? mainPath = ScriptingBridgeService.Current.FindInstalledMainPath();
            if (string.IsNullOrWhiteSpace(mainPath)) return null;
            // main.lua lives under ...\WinGDK\ue4ss\Mods\HaloMeister\Scripts\ — about
            // 8 parents up to the Store game root. Older code only walked 4 levels and
            // stopped inside WinGDK, missing Paks for Microsoft Store installs.
            return WalkToGameRoot(Path.GetDirectoryName(mainPath));
        }
        catch
        {
            return null;
        }
    }

    private static string? WalkToGameRoot(string? startDirectory)
    {
        string? directory = startDirectory;
        for (int i = 0; i < 10 && directory is not null; i++)
        {
            if (Directory.Exists(Path.Combine(directory, "Meteorite", "Content", "Paks")) ||
                Directory.Exists(Path.Combine(directory, "Content", "Meteorite", "Content", "Paks")))
            {
                return directory;
            }

            directory = Path.GetDirectoryName(directory);
        }

        return null;
    }
}

public sealed record FullPalettesOverlayResult(
    bool Installed,
    string PaksDirectory,
    IReadOnlyList<string> Files,
    string Message);

public sealed record BuiltinModFileStatus(string FileName, bool Present);

public enum BuiltinModSyncState
{
    BundleMissing,
    BundleTampered,
    GameFolderMissing,
    NotInstalled,
    Incomplete,
    Outdated,
    UpToDate,
}

public sealed record BuiltinModSyncStatus(
    BuiltinModSyncState State,
    bool CanInstall,
    bool CanRemove,
    bool NeedsUpdatePrompt,
    string Message);
