using System.Diagnostics;
using System.Security.Cryptography;
using HaloMeister.App.Localization;

namespace HaloMeister.App.Services;

/// <summary>
/// Installs a bundled IoStore overlay triplet into the game Paks folder.
/// The default instance is campaign extras <c>MMYJ_FULL_VEHI_WAP_P</c>
/// (vehicle/weapon/biped palettes, character-palette fill, dedicated
/// <c>hm_ally</c>/<c>hm_hostile</c> scaffolds). Character AI
/// (<c>MMYJ_FULL_CHAR_P</c>) is a separate package in
/// <see cref="BuiltinModCatalog"/>.
/// </summary>
public sealed class FullPalettesOverlayService
{
    public const string OverlayStem = "MMYJ_FULL_VEHI_WAP_P";
    public const string CharacterOverlayStem = "MMYJ_FULL_CHAR_P";

    private static readonly string[] Extensions = [".utoc", ".ucas", ".pak"];

    /// <summary>
    /// Trusted fingerprint of the campaign extras triplet
    /// (<c>length:SHA256</c> for .utoc|.ucas|.pak). Regenerated by
    /// <c>expand-palettes.ps1 -UpdateBundledAssets</c>.
    /// </summary>
    public const string ExpectedBundledFingerprint =
        "16736:5CA055837686C7B783599317D47BD1593ABD9FB4081CD1F48D251E495F86F3D3|83061758:46A131D44D9C0B3138ED20FF7F54A2793619C1E83FE19C4599059B6F112CE81D|339:B712C03A695E34CD522446B73C4F71644A402FF141EB19CE66C269FD5676AD8C";

    /// <summary>
    /// Trusted fingerprint of the character AI triplet. Empty until
    /// <c>expand-palettes.ps1 -UpdateBundledAssets</c> ships the split pack.
    /// </summary>
    public const string ExpectedCharacterFingerprint =
        "840:595AF479BA6BADD491675F7F8C32EE1E6B498F82460B30FE42E0F7B32AEC33D5|277141:4092B92371E4FAACC961A2F3D815DD754435F7EE0B40A242705E28533F56A746|339:B712C03A695E34CD522446B73C4F71644A402FF141EB19CE66C269FD5676AD8C";

    private static readonly object FingerprintCacheGate = new();
    private static string? _fingerprintCacheKey;
    private static string? _fingerprintCacheValue;

    private readonly BuiltinModDefinition _mod;

    public static IReadOnlyList<string> RequiredFileNames { get; } =
        Extensions.Select(extension => OverlayStem + extension).ToArray();

    public FullPalettesOverlayService()
        : this(BuiltinModCatalog.Campaign)
    {
    }

    public FullPalettesOverlayService(BuiltinModDefinition definition)
    {
        _mod = definition;
    }

    public BuiltinModDefinition Definition => _mod;

    public bool IsGameRunning =>
        Process.GetProcessesByName("HaloCampaignEvolved").Any(process => !process.HasExited);

    /// <summary>
    /// True only when all three overlay files are present in Paks.
    /// Dedicated features (Allegiance Demo scaffolds) should gate on the
    /// default campaign extras instance.
    /// </summary>
    public bool IsInstalled()
    {
        try
        {
            string paks = ResolvePaksDirectory();
            return HasCompleteTriplet(paks, _mod.Stem) ||
                   _mod.LegacyStems.Any(stem => HasCompleteTriplet(paks, stem));
        }
        catch (DirectoryNotFoundException)
        {
            return false;
        }
    }

    public bool IsBundledAvailable()
    {
        try
        {
            _ = ResolveBundledSources();
            return true;
        }
        catch (FileNotFoundException)
        {
            return false;
        }
    }

    /// <summary>
    /// True when the app-bundled triplet matches the trusted fingerprint for
    /// this build. Tampered or corrupt bundles must not drive update prompts.
    /// An empty expected fingerprint means the pack is not fingerprint-locked
    /// yet (used while the character AI overlay is being split out).
    /// </summary>
    public bool IsBundledIntact()
    {
        try
        {
            string[] sources = ResolveBundledSources();
            string? fingerprint = TryFingerprintFiles(sources);
            return IsTrustedFingerprint(fingerprint);
        }
        catch (FileNotFoundException)
        {
            return false;
        }
    }

    public static IReadOnlyList<BuiltinModCatalogStatus> GetCatalogStatuses()
    {
        return BuiltinModCatalog.All
            .Select(definition =>
            {
                var service = new FullPalettesOverlayService(definition);
                return new BuiltinModCatalogStatus(definition, service.GetSyncStatus());
            })
            .ToArray();
    }

    /// <summary>
    /// Compare bundled vs installed content. When the app bundle is tampered,
    /// returns <see cref="BuiltinModSyncState.BundleTampered"/> and never
    /// reports <see cref="BuiltinModSyncState.Outdated"/>.
    /// </summary>
    public BuiltinModSyncStatus GetSyncStatus()
    {
        string[]? bundledSources = null;
        try
        {
            bundledSources = ResolveBundledSources();
        }
        catch (FileNotFoundException)
        {
            return new BuiltinModSyncStatus(
                BuiltinModSyncState.BundleMissing,
                CanInstall: false,
                CanRemove: false,
                NeedsUpdatePrompt: false,
                L.Get("builtin_mod.bundle_missing"));
        }

        string? bundledFingerprint = TryFingerprintFiles(bundledSources);
        bool bundledIntact = IsTrustedFingerprint(bundledFingerprint);

        string? paks = null;
        try
        {
            paks = ResolvePaksDirectory();
        }
        catch (DirectoryNotFoundException)
        {
            if (!bundledIntact)
            {
                return new BuiltinModSyncStatus(
                    BuiltinModSyncState.BundleTampered,
                    CanInstall: false,
                    CanRemove: false,
                    NeedsUpdatePrompt: false,
                    L.Get("builtin_mod.bundle_tampered"));
            }

            return new BuiltinModSyncStatus(
                BuiltinModSyncState.GameFolderMissing,
                CanInstall: false,
                CanRemove: false,
                NeedsUpdatePrompt: false,
                L.Get("builtin_mod.game_folder_missing"));
        }

        IReadOnlyList<string> requiredNames = RequiredNames();
        int present = requiredNames.Count(name =>
            File.Exists(Path.Combine(paks, name)));
        bool shippingInstalled = HasCompleteTriplet(paks, _mod.Stem);
        bool legacyInstalled = _mod.LegacyStems.Any(stem =>
            HasCompleteTriplet(paks, stem));
        bool anyInstalledFiles = present > 0 ||
            _mod.LegacyStems.Any(stem =>
                Extensions.Any(extension =>
                    File.Exists(Path.Combine(paks, stem + extension))));

        if (!bundledIntact)
        {
            return new BuiltinModSyncStatus(
                BuiltinModSyncState.BundleTampered,
                CanInstall: false,
                CanRemove: anyInstalledFiles,
                NeedsUpdatePrompt: false,
                L.Get("builtin_mod.bundle_tampered"));
        }

        if (shippingInstalled)
        {
            string? installedFingerprint = TryFingerprintTriplet(paks, _mod.Stem);
            if (installedFingerprint is not null &&
                bundledFingerprint is not null &&
                string.Equals(
                    installedFingerprint,
                    bundledFingerprint,
                    StringComparison.Ordinal))
            {
                return new BuiltinModSyncStatus(
                    BuiltinModSyncState.UpToDate,
                    CanInstall: false,
                    CanRemove: true,
                    NeedsUpdatePrompt: false,
                    L.Get("builtin_mod.status_ready"));
            }

            return new BuiltinModSyncStatus(
                BuiltinModSyncState.Outdated,
                CanInstall: true,
                CanRemove: true,
                NeedsUpdatePrompt: true,
                L.Get("builtin_mod.status_outdated"));
        }

        if (legacyInstalled)
        {
            return new BuiltinModSyncStatus(
                BuiltinModSyncState.Outdated,
                CanInstall: true,
                CanRemove: true,
                NeedsUpdatePrompt: true,
                L.Get("builtin_mod.status_outdated"));
        }

        if (present == 0)
        {
            return new BuiltinModSyncStatus(
                BuiltinModSyncState.NotInstalled,
                CanInstall: true,
                CanRemove: anyInstalledFiles,
                NeedsUpdatePrompt: false,
                L.Get("builtin_mod.status_not_installed"));
        }

        return new BuiltinModSyncStatus(
            BuiltinModSyncState.Incomplete,
            CanInstall: true,
            CanRemove: true,
            NeedsUpdatePrompt: true,
            L.Format(
                "builtin_mod.status_incomplete",
                present,
                requiredNames.Count));
    }

    /// <summary>
    /// Per-file presence for the shipping stem in the game Paks folder.
    /// </summary>
    public IReadOnlyList<BuiltinModFileStatus> GetInstalledFileStatus()
    {
        string? paks = null;
        try { paks = ResolvePaksDirectory(); }
        catch (DirectoryNotFoundException) { }

        return RequiredNames()
            .Select(name => new BuiltinModFileStatus(
                name,
                paks is not null && File.Exists(Path.Combine(paks, name))))
            .ToArray();
    }

    private IReadOnlyList<string> RequiredNames() =>
        Extensions.Select(extension => _mod.Stem + extension).ToArray();

    private bool IsTrustedFingerprint(string? fingerprint)
    {
        if (fingerprint is null)
            return false;
        if (string.IsNullOrEmpty(_mod.ExpectedFingerprint))
            return true;
        return string.Equals(
            fingerprint,
            _mod.ExpectedFingerprint,
            StringComparison.Ordinal);
    }

    private static bool HasCompleteTriplet(string paks, string stem) =>
        Extensions.All(extension =>
            File.Exists(Path.Combine(paks, stem + extension)));

    private static string? TryFingerprintTriplet(string directory, string stem)
    {
        string[] paths = Extensions
            .Select(extension => Path.Combine(directory, stem + extension))
            .ToArray();
        return TryFingerprintFiles(paths);
    }

    private static string? TryFingerprintFiles(IReadOnlyList<string> paths)
    {
        try
        {
            string cacheKey = string.Join(
                '|',
                paths.Select(path =>
                {
                    var info = new FileInfo(path);
                    return $"{path}:{info.Length}:{info.LastWriteTimeUtc.Ticks}";
                }));
            lock (FingerprintCacheGate)
            {
                if (_fingerprintCacheKey == cacheKey &&
                    _fingerprintCacheValue is not null)
                {
                    return _fingerprintCacheValue;
                }
            }

            var parts = new List<string>(paths.Count);
            foreach (string path in paths)
            {
                var info = new FileInfo(path);
                using FileStream stream = File.OpenRead(path);
                byte[] hash = SHA256.HashData(stream);
                parts.Add($"{info.Length}:{Convert.ToHexString(hash)}");
            }

            string fingerprint = string.Join('|', parts);
            lock (FingerprintCacheGate)
            {
                _fingerprintCacheKey = cacheKey;
                _fingerprintCacheValue = fingerprint;
            }
            return fingerprint;
        }
        catch
        {
            return null;
        }
    }

    public FullPalettesOverlayResult Install()
    {
        EnsureGameClosed();
        string[] sources = ResolveBundledSources();
        string? bundledFingerprint = TryFingerprintFiles(sources);
        if (!IsTrustedFingerprint(bundledFingerprint))
        {
            throw new InvalidOperationException(
                L.Get("builtin_mod.bundle_tampered"));
        }

        string paks = ResolvePaksDirectory();
        foreach (string stem in _mod.LegacyStems)
            RemoveStem(paks, stem);
        RemoveStem(paks, _mod.Stem);
        string[] destinations = sources
            .Select(source => Path.Combine(paks, Path.GetFileName(source)))
            .ToArray();

        var copied = new List<string>();
        try
        {
            for (int index = 0; index < sources.Length; index++)
            {
                string temporary = destinations[index] + $".{Guid.NewGuid():N}.tmp";
                File.Copy(sources[index], temporary, false);
                File.Move(temporary, destinations[index], true);
                copied.Add(destinations[index]);
            }
        }
        catch
        {
            foreach (string file in copied)
            {
                try { File.Delete(file); }
                catch { }
            }
            throw;
        }

        return new FullPalettesOverlayResult(
            Installed: true,
            PaksDirectory: paks,
            Files: destinations,
            Message: L.Get("builtin_mod.installed_restart"));
    }

    public FullPalettesOverlayResult Remove()
    {
        EnsureGameClosed();
        string paks = ResolvePaksDirectory();
        var removed = new List<string>();
        removed.AddRange(RemoveStem(paks, _mod.Stem));
        foreach (string stem in _mod.LegacyStems)
            removed.AddRange(RemoveStem(paks, stem));

        if (removed.Count == 0)
            throw new FileNotFoundException(
                L.Get("builtin_mod.status_not_installed"));

        return new FullPalettesOverlayResult(
            Installed: false,
            PaksDirectory: paks,
            Files: removed,
            Message: L.Get("builtin_mod.removed_restart"));
    }

    private void EnsureGameClosed()
    {
        if (IsGameRunning)
            throw new InvalidOperationException(
                L.Get("builtin_mod.close_game"));
    }

    private static List<string> RemoveStem(string paks, string stem)
    {
        var removed = new List<string>();
        foreach (string extension in Extensions)
        {
            string path = Path.Combine(paks, stem + extension);
            if (!File.Exists(path)) continue;
            File.Delete(path);
            removed.Add(path);
        }
        return removed;
    }

    private string[] ResolveBundledSources()
    {
        string[] roots =
        [
            Path.Combine(AppContext.BaseDirectory, "Assets", "Overlays"),
            Path.Combine(AppContext.BaseDirectory, "Overlays"),
        ];
        foreach (string root in roots)
        {
            string[] candidates = Extensions
                .Select(extension => Path.Combine(root, _mod.Stem + extension))
                .ToArray();
            if (candidates.All(File.Exists))
                return candidates;
        }

        throw new FileNotFoundException(
            L.Get("builtin_mod.bundle_missing"));
    }

    public static string ResolvePaksDirectory()
    {
        string? discovered = GameInstallationService.Current.TryGetPaksDirectory();
        if (discovered is not null)
            return discovered;

        foreach (string root in CandidateGameRoots())
        {
            string full;
            try { full = Path.GetFullPath(root); }
            catch { continue; }

            string[] candidates =
            [
                Path.Combine(full, "Content", "Meteorite", "Content", "Paks"),
                Path.Combine(full, "Meteorite", "Content", "Paks"),
                Path.Combine(full, "Content", "Paks"),
                full,
            ];
            foreach (string candidate in candidates)
                if (Directory.Exists(candidate) &&
                    Directory.EnumerateFiles(candidate, "*.utoc").Any())
                    return candidate;
        }

        throw new DirectoryNotFoundException(
            L.Get("builtin_mod.game_folder_missing"));
    }

    private static IEnumerable<string> CandidateGameRoots()
    {
        string? remembered = TryRememberedGameRoot();
        if (!string.IsNullOrWhiteSpace(remembered))
            yield return remembered!;

        foreach (string root in GameInstallationService.Current.EnumerateCandidateRoots())
            yield return root;
    }

    private static string? TryRememberedGameRoot()
    {
        try
        {
            // Binary directory is already the WinGDK/Win64 folder; walking from there
            // reaches Content\Meteorite\Content\Paks in a few hops.
            string? binaryDirectory = GameInstallationService.Current.BinaryDirectory;
            if (!string.IsNullOrWhiteSpace(binaryDirectory))
            {
                string? fromBinary = WalkToGameRoot(binaryDirectory);
                if (fromBinary is not null)
                    return fromBinary;
            }

            string? mainPath = ScriptingBridgeService.Current.FindInstalledMainPath();
            if (string.IsNullOrWhiteSpace(mainPath)) return null;
            // main.lua lives under ...\WinGDK\ue4ss\Mods\HaloMeister\Scripts\ — about
            // 8 parents up to the Store game root. Older code only walked 4 levels and
            // stopped inside WinGDK, missing Paks for Microsoft Store installs.
            return WalkToGameRoot(Path.GetDirectoryName(mainPath));
        }
        catch
        {
            return null;
        }
    }

    private static string? WalkToGameRoot(string? startDirectory)
    {
        string? directory = startDirectory;
        for (int i = 0; i < 10 && directory is not null; i++)
        {
            if (Directory.Exists(Path.Combine(directory, "Meteorite", "Content", "Paks")) ||
                Directory.Exists(Path.Combine(directory, "Content", "Meteorite", "Content", "Paks")))
            {
                return directory;
            }

            directory = Path.GetDirectoryName(directory);
        }

        return null;
    }
}

public sealed record FullPalettesOverlayResult(
    bool Installed,
    string PaksDirectory,
    IReadOnlyList<string> Files,
    string Message);

public sealed record BuiltinModFileStatus(string FileName, bool Present);

public sealed record BuiltinModCatalogStatus(
    BuiltinModDefinition Definition,
    BuiltinModSyncStatus Sync);

public enum BuiltinModSyncState
{
    BundleMissing,
    BundleTampered,
    GameFolderMissing,
    NotInstalled,
    Incomplete,
    Outdated,
    UpToDate,
}

public sealed record BuiltinModSyncStatus(
    BuiltinModSyncState State,
    bool CanInstall,
    bool CanRemove,
    bool NeedsUpdatePrompt,
    string Message);
